apiVersion: v2
name: rapidfort
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.1.40 

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: 1.1.40
dependencies:
- repository: "file://deps/backend/"
  version: 1.1.0
  name: backend
  condition: backend.enabled
- repository: "file://deps/iso-master/"
  version: 1.1.0
  name: iso-master
  condition: iso-master.enabled  
- repository: "file://deps/rf-scan/"
  version: 1.1.0
  name: rf-scan
  condition: rf-scan.enabled
- repository: "file://deps/frontrow/"
  version: 1.1.0
  name: frontrow
  condition: frontrow.enabled
- repository: "file://deps/rfapi/"
  version: 1.1.0
  name: rfapi
  condition: rfapi.enabled
- repository: "file://deps/rfpubsub/"
  version: 1.1.0
  name: rfpubsub
  condition: rfpubsub.enabled
- repository: "file://deps/aggregator/"
  version: 1.1.0
  name: aggregator
  condition: aggregator.enabled
- repository: "file://deps/keycloak/"
  version: 1.1.0
  name: keycloak
  condition: keycloak.enabled
- repository: "file://deps/redis/"
  version: 1.1.0
  name: redis
  condition: redis.enabled
- repository: "file://deps/files-redis/"
  version: 1.1.0
  name: files-redis
  condition: files-redis.enabled
- repository: "file://deps/lock-redis/"
  version: 1.1.0
  name: lock-redis
  condition: lock-redis.enabled    
- repository: "file://deps/mysql/"
  version: 1.1.0
  name: mysql
  condition: mysql.enabled
- repository: "file://deps/runner/"
  version: 1.1.0
  name: runner
  condition: runner.enabled
- repository: "file://deps/vulns-db/"
  version: 1.1.0
  name: vulns-db
  condition: vulns-db.enabled
- repository: "file://deps/fileupload/"
  version: 1.1.0
  name: fileupload
  condition: fileupload.enabled
- repository: "file://deps/fluent-bit/"
  version: 1.1.0
  name: fluent-bit
  condition: logger.enabled
