apiVersion: v1
kind: Secret
metadata:
  name: rf-secret
  labels:
    {{- include "rapidfort.labels" . | nindent 4 }}
type: "Opaque"
data:
  AWS_ACCESS_KEY_ID: {{ default "" .Values.secret.aws_access_key_id | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ default "" .Values.secret.aws_secret_access_key | b64enc | quote }}
  AWS_DEFAULT_REGION: {{ default "" .Values.secret.aws_default_region | b64enc | quote }}          
  RF_ROLE_ARN: {{ default "" .Values.secret.aws_role_arn | b64enc | quote }}
  RF_S3_BUCKET: {{ default "" .Values.secret.s3_bucket | b64enc | quote }}
  USERNAME_SMTP: {{ default "" .Values.secret.smtp_username | b64enc | quote }}
  PASSWORD_SMTP: {{ default "" .Values.secret.smtp_password | b64enc | quote }}
  SOURCE_ARN: {{ default "" .Values.secret.smtp_source_arn | b64enc | quote }}  
  KEYCLOAK_JWT_PUB_KEY: {{ default "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAt0EwFCzsmzWgn7A8A40hzX1kPHab0WZTmUF8OwHt7fyds6sBiSDPnLIh0BgmXIO2WIrGzARm9dVUeAWI/aUI7qucfgYgW7XSwwz7X/IrX6DExsNZzTLxgIfDJR/WP0fo1vO10BQDAtJxEkX5YvFitBFzg4FLKMZP5inAFM21+jfjD2ufi7NWTyFJR6YCLGFma29XHE75yE76+Xq8eH3DI/8xmrU5hw1Yk5GrABf4KYTijsp+QLQZkEycYvfJEPEMigwnARdp6C3VDp/T8OL1hb2YtrZ4vjZ80azEicQ3ea/R05JK6ikfik2SlC5Rm0Ore0Rh4jB1tI51biVa0smsiwIDAQAB" .Values.secret.keycloak_jwt_pub_key | b64enc | quote }}      
  KEYCLOAK_CLIENT_ID: {{ default "scanners" .Values.secret.keycloak_client_id | b64enc | quote }}
  KEYCLOAK_REALM: {{ default "customers" .Values.secret.keycloak_realm | b64enc | quote }}
  KEYCLOAK_SERVICE_ACCOUNT_CLIENT_ID: {{ default "admin-cli" .Values.secret.keycloak_service_account_client_id | b64enc | quote }}
  KEYCLOAK_SERVICE_ACCOUNT_CLIENT_SECRET: {{ default "5b97220c-838a-4186-bcdd-8cdb77d0e0f3" .Values.secret.keycloak_service_account_client_secret | b64enc | quote }}
  DB_URL: {{ default "mysql+mysqldb://root:RF-123579@mysql/standalone" .Values.secret.db_url | b64enc | quote }}
  ADMIN_ROLE_ID: {{ default "27d3ab99-d8f0-4eb2-bdd5-3b5091eb97bd" .Values.secret.admin_role_id | b64enc | quote }}
  MEMBER_ROLE_ID: {{ default "b653c6eb-2e67-4322-a58e-14e110199215" .Values.secret.member_role_id | b64enc | quote }}
  GUEST_ROLE_ID: {{ default "5b11397f-db4d-4f98-b3c8-a810e165b55c" .Values.secret.guest_role_id | b64enc | quote }}
  SUPER_ADMIN_ROLE_ID: {{ default "511cbb43-1a52-4088-9c74-ef7e8ff6027a" .Values.secret.guest_role_id | b64enc | quote }}
  RF_APP_HOST: {{ default "" .Values.secret.rf_app_host | b64enc | quote}}
  RF_APP_ADMIN: {{ default "" .Values.secret.rf_app_admin | b64enc | quote}}
  RF_APP_ADMIN_PASSWD: {{ default "" .Values.secret.rf_app_admin_passwd | b64enc | quote}}
  DEPLOY_MODE: {{ default "STANDALONE" .Values.secret.deploy_mode | b64enc | quote}}
  RF_VERBOSE: {{ default "0" .Values.secret.rf_verbose| toString | b64enc | quote }}
