apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mysql.fullname" . }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mysql.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "mysql.fullname" . }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mysql.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mysql.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: mysql-data
          hostPath:
            path: /opt/rapidfort/data/shared/mysql
        - name: mysql-initdb
          configMap:
            name: mysql-initdb-config
      initContainers:
        - name: volume-permissions
          image: public.ecr.aws/rapidfort/init:1.1.10
          command:
          - /bin/bash
          - -c
          - chmod 777 /bitnami/mysql
          volumeMounts:
            - name: mysql-data
              mountPath: "/bitnami/mysql"
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MYSQL_DATABASE
              value: "keycloak"
            - name: MYSQL_AUTHENTICATION_PLUGIN
              value: mysql_native_password
            - name: MYSQL_ROOT_PASSWORD
              value: "RF-123579"
          volumeMounts:
            - name: mysql-data
              mountPath: "/bitnami/mysql"
            - name: mysql-initdb
              mountPath: /docker-entrypoint-initdb.d
          ports:
            - name: mysql
              containerPort: 3306
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - "mysql"
                - "--host=localhost"
                - "--user=root"
                - "--password=RF-123579"
                - "-e"
                - "SHOW DATABASES;"
            failureThreshold: 99
            periodSeconds: 99
            successThreshold: 1
            timeoutSeconds: 99
          readinessProbe:
            exec:
              command:
                - "mysql"
                - "--host=localhost"
                - "--user=root"
                - "--password=RF-123579"
                - "-e"
                - "SHOW DATABASES;"
            initialDelaySeconds: 4
            periodSeconds: 99
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
