apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-read
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["deployments", "pods", "namespaces"]
  verbs: ["get", "list", "watch"]

