apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  labels:
    app: {{ .Release.Name }}
data:
  fluent-bit.conf: |
    [SERVICE]
        Parsers_File parsers.conf

    @INCLUDE input-*.conf
    @INCLUDE output-*.conf

    @INCLUDE filters.conf
  
  parsers.conf: |
    [PARSER]
        Name        kubernetes-tag
        Format      regex
        Regex       (?<namespace_name>.+)\.(?<pod_name>.+)\.(?<container_name>.+)

  input-s3logs.conf: |
    [INPUT]
        Name              tail
        Tag               kube.<namespace_name>.<pod_name>.<container_name>
        Tag_Regex         (?<pod_name>[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace_name>[^_]+)_(?<container_name>.+)-
        Path              /var/log/containers/*.log
        Exclude_Path      /var/log/containers/*_logger_*.log
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10

  output-s3.conf: |
    [OUTPUT]
        Name              s3
        Match             *
        bucket            {{ default .Values.env.rf_s3_bucket .Values.secret.s3_bucket | quote}}
        region            {{ default .Values.env.aws_default_region .Values.secret.aws_default_region | quote }}
        use_put_object    On
        s3_key_format     /{{ default .Values.env.rf_app_host .Values.secret.rf_app_host }}/log/$TAG[1]/$TAG[3]/%Y%m%d/$UUID.gz
        s3_key_format_tag_delimiters  .
        total_file_size   5M
        upload_timeout    1m

    [OUTPUT]
        Name  stdout
        Match *

  filters.conf: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.
        Merge_Log           On
        Merge_Log_Key       log_processed
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On
        Regex_Parser        kubernetes-tag
        Labels              Off
        Annotations         Off

