apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "frontrow.fullname" . }}
  labels:
    {{- include "frontrow.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "frontrow.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "frontrow.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "frontrow.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
      {{ if .Values.extraVolumes }}
      {{ tpl (toYaml (index .Values.extraVolumes )) . | nindent 6 }}
      {{ end }}  
      {{ if .Values.volumes }}
      {{ tpl (toYaml (index .Values.volumes )) . | nindent 6 }}
      {{ end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{ if .Values.container.extra_options }}
          {{- toYaml .Values.container.extra_options | nindent 10 }}
          {{ end }}
          env:
            {{ if .Values.secret.name }}
            {{- $secretName := .Values.secret.name }}
            {{- range .Values.secret.keys }}
            - name: {{ . | quote}}
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: {{ . | quote}}
            {{- end }}
            {{- end }}           
          volumeMounts:
          {{ if .Values.extraVolumeMounts }}
          {{ tpl (toYaml (index .Values.extraVolumeMounts )) . | nindent 12 }}
          {{ end }}
          {{ if .Values.volumeMounts }}
          {{ tpl (toYaml (index .Values.volumeMounts )) . | nindent 12 }}
          {{ end }}
          ports:
            - name: frontrow-http
              containerPort: {{ .Values.service.container_port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
            {{- toYaml .Values.probeCommand | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
            {{- toYaml .Values.probeCommand | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
