apiVersion: v1
kind: Service
metadata:
  name: {{ include "rfpubsub.fullname" . }}
  labels:
    {{- include "rfpubsub.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: rfpubsub-http
      protocol: TCP
      name: http
  selector:
    {{- include "rfpubsub.selectorLabels" . | nindent 4 }}