{{- if .Values.redis_config.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: lock-redis-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lock-redis.selectorLabels" . | nindent 4 }}
data:
  {{ (tpl (.Files.Glob "config_map/*.conf").AsConfig $ ) | nindent 2 }}
{{- end }}
