apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "backend.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "backend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:          
      {{ if .Values.volumes }}
      {{ tpl (toYaml (index .Values.volumes )) . | nindent 6 }}
      {{ end }}
      {{ if .Values.extraVolumes }}
      {{ tpl (toYaml (index .Values.extraVolumes )) . | nindent 6 }}
      {{ end }}
      initContainers:
        - name: init
          image: public.ecr.aws/rapidfort/init:1.1.10
          command:
            - "/bin/bash"
            - "-c"
            - "until [ $(curl --connect-timeout 1 -sw '%{http_code}' http://{{ .Values.keycloak.serviceName }} -o /dev/null) -eq 200 ]; do echo keycloak not ready; sleep 1; done"
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{ if .Values.container.extra_options }}
          {{- toYaml .Values.container.extra_options | nindent 10 }}
          {{ end }}
          env:
            - name: LC_ALL
              value: "en_US.UTF-8"          
            - name: BACKEND_APP_PORT
              value: "{{ .Values.service.container_port }}"
            - name: AUTH_SERVER_ROOT_URL
              value: "http://{{ .Values.keycloak.serviceName }}"
            - name: COMMUNITY_USER_ID
              value: {{ default "" .Values.env.communityUserId | quote}}
            - name: COMMUNITY_ORG_ID
              value: {{ default "" .Values.env.communityOrgId | quote }}
            - name: CLOUDVM_ORCHESTRATOR_SERVICE_HOST
              value: "cloudvm-orchestrator"
            - name: CLOUDVM_ORCHESTRATOR_SERVICE_PORT
              value: "80"
            #NOTE: not using secret as secret goes for all the containers.
            - name: RF_DEBUG
              value:  "{{ .Values.env.rf_debug }}"
            - name: RF_VERSION_FILE
              value:  "/opt/rapidfort/env.config"
            #inject create values as env variable.
            {{ if .Values.secret.name }}
            {{- $secretName := .Values.secret.name }}
            {{- range .Values.secret.keys }}
            - name: {{ . | quote}}
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: {{ . | quote}}
            {{- end }}
            {{ end }}
          volumeMounts:
            {{ if .Values.volumeMounts }}
            {{ tpl (toYaml (index .Values.volumeMounts )) . | nindent 12 }}
            {{ end }}
            {{ if .Values.extraVolumeMounts }}
            {{ tpl (toYaml (index .Values.extraVolumeMounts )) . | nindent 12 }}
            {{ end }}
          ports:
            - name: backend-http
              containerPort: {{ .Values.service.container_port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
            {{- toYaml .Values.probeCommand | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
            {{- toYaml .Values.probeCommand | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
