apiVersion: v1
kind: Service
metadata:
  name: community-service
spec:
  type: ExternalName
  externalName: api.rapidfort.com
  ports:
  - port: 443
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: community-service
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/upstream-vhost: api.rapidfort.com
spec:
  rules:
  - http:
      paths:
      - backend:
          service: 
            name: community-service
            port:
              number: 443
        path: /api/v1/community/.*
        pathType: ImplementationSpecific
      - backend:
          service: 
            name: community-service
            port:
              number: 443
        path: /api/v1/imgs_work_dir/7b2f45e2-03f9-45bf-b301-136e8b136338/.*
        pathType: ImplementationSpecific




