apiVersion: v1
kind: Service
metadata:
  name: community-service
  namespace: {{ .Release.Namespace }}
spec:
  type: ExternalName
  externalName: {{ default .Values.allowed_rf_host .Values.global.allowed_rf_host }}
  ports:
  - port: 443
---
{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: community-service
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/upstream-vhost: {{ default .Values.allowed_rf_host .Values.global.allowed_rf_host }}
spec:
  ingressClassName: {{ default .Values.ingress.className .Values.global.ingressClassName }}
  rules:
  - http:
      paths:
      - backend:
          service: 
            name: community-service
            port:
              number: 443
        path: /api/v1/community/.*
        pathType: ImplementationSpecific
      - backend:
          service: 
            name: community-service
            port:
              number: 443
        path: /api/v1/imgs_work_dir/7b2f45e2-03f9-45bf-b301-136e8b136338/.*
        pathType: ImplementationSpecific
{{- end }}