apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rfapi.fullname" . }}
  labels:
    {{- include "rfapi.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "rfapi.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "rfapi.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      {{ if .Values.volumes }}
      {{ tpl (toYaml (index .Values.volumes )) . | nindent 6 }}
      {{ end }}
      {{ if .Values.extraVolumes }}
      {{ tpl (toYaml (index .Values.extraVolumes )) . | nindent 6 }}
      {{ end }}
      serviceAccountName: {{ include "rfapi.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: init-host-redis-check
          image: public.ecr.aws/rapidfort/init
          command:
            - "/bin/bash"
            - "-c"
            - "until [ $(redis-cli -h {{ .Values.env.redis_host_locks }} -p {{ .Values.env.redis_port }} ping) == 'PONG' ]; do echo redis not ready; sleep 1; done"
        - name: init-files-redis-check
          image: public.ecr.aws/rapidfort/init
          command:
            - "/bin/bash"
            - "-c"
            - "until [ $(redis-cli -h {{ .Values.env.redis_host_files }} -p {{ .Values.env.redis_port }} ping) == 'PONG' ]; do echo redis not ready; sleep 1; done"            
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{ if .Values.container.extra_options }}
          {{- toYaml .Values.container.extra_options | nindent 10 }}
          {{ end }}          
          ports:
            - name: rfapi-http
              containerPort: {{ .Values.service.container_port }}
              protocol: TCP
          volumeMounts:
            {{ if .Values.volumeMounts }}
            {{ tpl (toYaml (index .Values.volumeMounts )) . | nindent 12 }}
            {{ end }}
            {{ if .Values.extraVolumeMounts }}
            {{ tpl (toYaml (index .Values.extraVolumeMounts )) . | nindent 12 }}
            {{ end }}      
          env:
            - name: LC_ALL
              value: "en_US.UTF-8"          
            - name: RF_API_PORT
              value: "{{ .Values.service.container_port }}"
            - name: "RF_DEBUG"
              value: "{{ .Values.env.rf_debug }}"
            - name: RF_REDIS_HOST_NAME
              value: "{{ .Values.env.redis_host }}"
            - name: RF_REDIS_HOST_NAME_LOCKS
              value: "{{ .Values.env.redis_host_locks }}"
            - name: RF_REDIS_HOST_NAME_FILES
              value: "{{ .Values.env.redis_host_files }}"
            - name: RF_REDIS_PORT
              value: "{{ .Values.env.redis_port }}"
            - name: RF_REDIS_PWD
              value: "{{ .Values.env.redis_pwd }}"
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
            {{- toYaml .Values.probeCommand | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
            {{- toYaml .Values.probeCommand | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
