{{- if .Values.autoscaling.enabled }}
apiVersion: {{ include "rf-scan.autoscaler.apiVersion" . }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "rf-scan.fullname" . }}
  labels:
    {{- include "rf-scan.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "rf-scan.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: "Utilization"
          averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    # {{- if .Values.autoscaling.targetMemoryUtilizationPercentage }}
    # - type: Resource
    #   resource:
    #     name: memory
    #     target:
    #       type: "Utilization"
    #       averageUtilization: {{ .Values.autoscaling.targetMemoryUtilizationPercentage }}
    # {{- end }}
{{- end }}
