apiVersion: v1
kind: Service
metadata:
  name: {{ include "rf-scan.fullname" . }}
  labels:
    {{- include "rf-scan.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: rf-scan-http
      protocol: TCP
      name: http
  selector:
    {{- include "rf-scan.selectorLabels" . | nindent 4 }}
