apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "files-redis.fullname" . }}
  labels:
    {{- include "files-redis.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "files-redis.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "files-redis.fullname" . }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "files-redis.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "files-redis.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
      {{ if .Values.volumes }}
      {{ tpl (toYaml (index .Values.volumes )) . | nindent 6 }}
      {{ end }}
      initContainers:
        - name: volume-permissions
          image: public.ecr.aws/rapidfort/init:1.1.10
          command:
          - /bin/bash
          - -c
          - chmod 777 /bitnami/redis/data/
          volumeMounts:
          {{ if .Values.volumeMounts }}
          {{ tpl (toYaml (index .Values.volumeMounts )) . | nindent 12 }}
          {{ end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          volumeMounts:
          {{ if .Values.volumeMounts }}
          {{ tpl (toYaml (index .Values.volumeMounts )) . | nindent 12 }}
          {{ end }}
          livenessProbe:
            exec:
              command:
              - redis-cli
              - ping
            initialDelaySeconds: 4
            failureThreshold: 99
            timeoutSeconds: 99
            periodSeconds: 99
          readinessProbe:
            exec:
              command:
              - redis-cli
              - ping
            initialDelaySeconds: 4
            timeoutSeconds: 99
            periodSeconds: 99
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
