# Default values for iso-master.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: 274057717848.dkr.ecr.us-east-1.amazonaws.com/iso-master
  pullPolicy: IfNotPresent

global:
  rf_app_host:
  container_engine: "docker"

tunnelStubendabled: false
env:
  #Tunnel Stub variables. - START
  ami_image_id: "ami-06fb837f38439836e"
  vm_scheduler_port: 80
  vm_server_addr: vm-scheduler
  vmpool_server_addr: ""
  security_group_id: "sg-0cb2f23f1b8da8468"
  vpc_subnet_id: "subnet-0f8c9a907f6bb6c94"
  #Tunnel Stub variables. - END
  backend_service_name: "backend"
  debug: off
  rf_debug: false
  redis_host: "redis"
  redis_host_locks: lock-redis
  redis_host_files: files-redis  
  redis_port: "6379"
  redis_pwd: "" 
  redis_host_ha: "redis"
  redis_port_ha: "6379"
  redis_pwd_ha: ""
  redis_db_ha: 4  
  gcp-cred: ""

imagePullSecrets: []
nameOverride: "iso-master"
fullnameOverride: "iso-master"

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

podAnnotations: {}

podSecurityContext:
  fsGroup: 412

securityContext:
  privileged: true
  capabilities:
    add:
    #TODO: confirm the permission.
    - SYS_ADMIN

service:
  type: ClusterIP
  port: 80
  container_port: 8080

ingress:
  enabled: true
  className: ""
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
  hosts:
    - host: 
      paths:
        - path: /iso-master/.*
          pathType: ImplementationSpecific
  tls: []

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  requests:
    cpu: 600m
    memory: 1024Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

tolerations: []

affinity: {}

nodeSelector: {}

#TODO: use this in template.
livenessProbe:
  periodSeconds: 10 
  initialDelaySeconds: 5
  timeoutSeconds: 99
  failureThreshold: 77

probeCommand:  
  httpGet:
    path: /
    port: isomaster-http

readinessProbe:
  periodSeconds: 10
  initialDelaySeconds: 5
  timeoutSeconds: 99
  failureThreshold: 77

keycloak:
  serviceName: keycloak-http

secret:
  name: "rf-secret"
  keys:
    - AWS_DEFAULT_REGION
    - DB_URL
    - RF_S3_BUCKET
    - RF_STORAGE_TYPE
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - RF_ROLE_ARN
    - RF_GS_CREDS
    - KEYCLOAK_JWT_PUB_KEY
    - KEYCLOAK_REALM
    - KEYCLOAK_CLIENT_ID
    - KEYCLOAK_SERVICE_ACCOUNT_CLIENT_ID
    - KEYCLOAK_SERVICE_ACCOUNT_CLIENT_SECRET
    - RF_APP_HOST
    - DEPLOY_MODE
    - RF_VERBOSE
    - RF_AZURE_CONNECTION_STRING    

volumes:
  - name: imgs-work-dir
    hostPath:
      path: /opt/rapidfort/data/shared/imgs_work_dir
  - name: image-db
    hostPath:
      path: /opt/rapidfort/data/shared/image_db
  - name: local-bucket
    hostPath:
      path: /opt/rapidfort/local-bucket/

volumeMounts:
  - name: imgs-work-dir
    mountPath: "/opt/rapidfort/iso-master/app/imgs_work_dir"
  - name: image-db
    mountPath: "/opt/rapidfort/iso-master/app/image_db"
  - name: local-bucket
    mountPath: "/opt/rapidfort/local-bucket"

container:
  extra_options: {}

init_containers:
  - name: init-vulns
    image: public.ecr.aws/rapidfort/init
    command:
      - "/bin/bash"
      - "-c"
      - "until [ $(curl --connect-timeout 1 -sw '%{http_code}' http://vulns-db/vulns-db/api/v1/vulnsdb -o /dev/null) -eq 200 ]; do echo vulns-db not ready; sleep 1; done"
  - name: init-backend
    image: public.ecr.aws/rapidfort/init
    command:
      - "/bin/bash"
      - "-c"
      - "until [ $(curl --connect-timeout 1 -sw '%{http_code}' http://backend -o /dev/null) -eq 200 ]; do echo backend not ready; sleep 1; done"